title: Brandon Chisnell
#logo: /assets/img/headshot_circle.png
description: Data Analyst
## LinkedIn
[Brandon's LinkedIn Page](https://www.linkedin.com/in/brandon-chisnell-9890a79b/)

## Resume
Link
show_downloads: false
theme: jekyll-theme-minimal
