title: Brandon Chisnell
#logo: /assets/img/headshot_circle.png
description: Data Analyst [LinkedIn Page](https://www.linkedin.com/in/brandon-chisnell-9890a79b/)
show_downloads: false
theme: jekyll-theme-minimal
